/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/** Starts the fruit-and-faults application. */
public class App {
  /**
   * Returns the initial greeting.
   *
   * @return greeting text
   */
  public String getGreeting() {
    return "Hello World!";
  }

  /**
   * Runs the application.
   *
   * @param args command-line arguments
   */
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
