import net.ltgt.gradle.errorprone.errorprone

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    checkstyle
    jacoco
    alias(libs.plugins.errorprone)
    alias(libs.plugins.spotless)
}

version = "0.1.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    errorprone(libs.errorprone.core)
    errorprone(libs.nullaway)

    compileOnly(libs.jspecify)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.jackson.databind)
    implementation(libs.jackson.datatype.jdk8)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

spotless {
    java {
        googleJavaFormat(
            libs.versions.google.java.format
                .get(),
        )
        formatAnnotations()
        importOrder("#", "java", "javax", "")
    }

    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}

checkstyle {
    toolVersion = libs.versions.checkstyle.get()
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
    maxWarnings = 0
}

tasks.withType<JavaCompile>().configureEach {
    options.errorprone {
        disableWarningsInGeneratedCode.set(true)
        error("NullAway")
        option("NullAway:OnlyNullMarked", "true")
    }
}

application {
    mainClass = "org.fruitandfaults.cli.FruitAndFaults"
    applicationName = "fruit-and-faults"
}

val generateCliVersion =
    tasks.register("generateCliVersion") {
        val cliVersion = project.version.toString()
        val outputDirectory = layout.buildDirectory.dir("generated/resources/cli-version")
        inputs.property("cliVersion", cliVersion)
        outputs.dir(outputDirectory)
        doLast {
            val outputFile = outputDirectory.get().file("cli-version.txt").asFile
            outputFile.parentFile.mkdirs()
            outputFile.writeText("$cliVersion\n", Charsets.UTF_8)
        }
    }

sourceSets.main {
    resources.srcDir(generateCliVersion)
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    classDirectories.setFrom(
        sourceSets.main
            .get()
            .output.classesDirs,
    )
    reports {
        html.required = true
        xml.required = true
    }
}

tasks.jacocoTestCoverageVerification {
    dependsOn(tasks.test)
    classDirectories.setFrom(
        sourceSets.main
            .get()
            .output.classesDirs,
    )
    violationRules {
        rule {
            limit {
                counter = "LINE"
                value = "COVEREDRATIO"
                minimum = "0.80".toBigDecimal()
            }
        }
    }
}

tasks.check {
    dependsOn(tasks.jacocoTestCoverageVerification)
}
