import net.ltgt.gradle.errorprone.errorprone
import org.fruitandfaults.build.CliEnvironmentTask
import org.fruitandfaults.build.InstallCliTask
import org.fruitandfaults.build.UninstallCliTask
import org.fruitandfaults.build.UpdateCliPathTask
import org.fruitandfaults.build.VerifyCliTask
import org.fruitandfaults.build.VerifyJdkTask

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    checkstyle
    jacoco
    alias(libs.plugins.errorprone)
    alias(libs.plugins.spotless)
}

version = "0.1.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    errorprone(libs.errorprone.core)
    errorprone(libs.nullaway)

    compileOnly(libs.jspecify)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.jackson.databind)
    implementation(libs.jackson.datatype.jdk8)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

spotless {
    java {
        googleJavaFormat(
            libs.versions.google.java.format
                .get(),
        )
        formatAnnotations()
        importOrder("#", "java", "javax", "")
    }

    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}

checkstyle {
    toolVersion = libs.versions.checkstyle.get()
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
    maxWarnings = 0
}

tasks.withType<JavaCompile>().configureEach {
    options.errorprone {
        disableWarningsInGeneratedCode.set(true)
        error("NullAway")
        option("NullAway:OnlyNullMarked", "true")
    }
}

application {
    mainClass = "org.fruitandfaults.cli.FruitAndFaults"
    applicationName = "fruit-and-faults"
}

val generateCliVersion =
    tasks.register("generateCliVersion") {
        val cliVersion = project.version.toString()
        val outputDirectory = layout.buildDirectory.dir("generated/resources/cli-version")
        inputs.property("cliVersion", cliVersion)
        outputs.dir(outputDirectory)
        doLast {
            val outputFile = outputDirectory.get().file("cli-version.txt").asFile
            outputFile.parentFile.mkdirs()
            outputFile.writeText("$cliVersion\n", Charsets.UTF_8)
        }
    }

sourceSets.main {
    resources.srcDir(generateCliVersion)
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    classDirectories.setFrom(
        sourceSets.main
            .get()
            .output.classesDirs,
    )
    reports {
        html.required = true
        xml.required = true
    }
}

tasks.jacocoTestCoverageVerification {
    dependsOn(tasks.test)
    classDirectories.setFrom(
        sourceSets.main
            .get()
            .output.classesDirs,
    )
    violationRules {
        rule {
            limit {
                counter = "LINE"
                value = "COVEREDRATIO"
                minimum = "0.80".toBigDecimal()
            }
        }
    }
}

tasks.check {
    dependsOn(tasks.jacocoTestCoverageVerification)
}

tasks.withType<CliEnvironmentTask>().configureEach {
    group = "CLI installation"
    osName.set(providers.gradleProperty("cliOsName").orElse(providers.systemProperty("os.name")))
    userHome.set(providers.gradleProperty("cliUserHome").orElse(providers.systemProperty("user.home")))
    localAppData.set(providers.gradleProperty("cliLocalAppData").orElse(providers.environmentVariable("LOCALAPPDATA")).orElse(""))
    xdgDataHome.set(providers.gradleProperty("cliXdgDataHome").orElse(providers.environmentVariable("XDG_DATA_HOME")).orElse(""))
    shell.set(providers.gradleProperty("cliShell").orElse(providers.environmentVariable("SHELL")).orElse(""))
    installRoot.set(providers.gradleProperty("cliInstallRoot").orElse(""))
    profileFile.set(providers.gradleProperty("cliProfile").orElse(""))
    currentPath.set(providers.gradleProperty("cliCurrentPath").orElse(providers.environmentVariable("PATH")).orElse(""))
    userPathFile.set(providers.gradleProperty("cliUserPathFile").orElse(""))
    javaHome.set(
        providers
            .gradleProperty(
                "cliJavaHome",
            ).orElse(providers.environmentVariable("JAVA_HOME"))
            .orElse(providers.systemProperty("java.home")),
    )
    cliVersion.set(project.version.toString())
    force.set(providers.gradleProperty("cliForce").map { it == "true" }.orElse(false))
}

val verifyJdk =
    tasks.register<VerifyJdkTask>("verifyJdk") {
        description = "Verifies local java and javac 26 without downloading a JDK."
    }
val installCli =
    tasks.register<InstallCliTask>("installCli") {
        description = "Installs the CLI to a dedicated marker-owned user directory."
        dependsOn(verifyJdk, tasks.installDist)
        distribution.set(layout.buildDirectory.dir("install/fruit-and-faults"))
    }
tasks.installDist { mustRunAfter(verifyJdk) }
tasks.withType<JavaCompile>().configureEach { mustRunAfter(verifyJdk) }
val addCliToPath =
    tasks.register<UpdateCliPathTask>("addCliToPath") {
        description = "Exposes the installed command via user PATH or an owned Unix command/profile block."
        dependsOn(installCli)
    }
val verifyCli =
    tasks.register<VerifyCliTask>("verifyCli") {
        description = "Runs the installed launcher with --version and a bounded deadline."
        dependsOn(addCliToPath)
    }
tasks.register("setupCli") {
    group = "CLI installation"
    description = "Verifies JDK 26, installs, exposes, and verifies the CLI."
    dependsOn(verifyCli)
}
tasks.register<UninstallCliTask>("uninstallCli") {
    description = "Removes only a matching owned installation/command/profile; requires -PcliForce=true."
}
