/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void mainPrintsGreeting() {
    PrintStream originalOut = System.out;
    ByteArrayOutputStream output = new ByteArrayOutputStream();

    try {
      System.setOut(new PrintStream(output, true, StandardCharsets.UTF_8));
      App.main(new String[0]);
    } finally {
      System.setOut(originalOut);
    }

    assertEquals("Hello World!" + System.lineSeparator(), output.toString(StandardCharsets.UTF_8));
  }
}
